version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - PORT=${BACKEND_PORT:-3000}
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
